admin_utilisateur_fonction_index:
    path:     /
    defaults: { _controller: "UtilisateurBundle:Fonction:index" }
    methods:  GET

admin_utilisateur_fonction_show:
    path:     /{id}/show
    defaults: { _controller: "UtilisateurBundle:Fonction:show" }
    methods:  GET

admin_utilisateur_fonction_new:
    path:     /new
    defaults: { _controller: "UtilisateurBundle:Fonction:new" }
    methods:  [GET, POST]

admin_utilisateur_fonction_edit:
    path:     /{id}/edit
    defaults: { _controller: "UtilisateurBundle:Fonction:edit" }
    methods:  [GET, POST]

admin_utilisateur_fonction_delete:
    path:     /{id}/delete
    defaults: { _controller: "UtilisateurBundle:Fonction:delete" }
    methods:  DELETE
