admin_utilisateur_utilisateur_index:
    path:     /
    defaults: { _controller: "UtilisateurBundle:Utilisateur:index" }

admin_utilisateur_utilisateur_show:
    path:     /{id}/show
    defaults: { _controller: "UtilisateurBundle:Utilisateur:show" }

admin_utilisateur_utilisateur_new:
    path:     /new
    defaults: { _controller: "UtilisateurBundle:Utilisateur:new" }

admin_utilisateur_utilisateur_create:
    path:     /create
    defaults: { _controller: "UtilisateurBundle:Utilisateur:create" }
    requirements: { _method: post }

admin_utilisateur_utilisateur_edit:
    path:     /{id}/edit
    defaults: { _controller: "UtilisateurBundle:Utilisateur:edit" }

admin_utilisateur_utilisateur_update:
    path:     /{id}/update
    defaults: { _controller: "UtilisateurBundle:Utilisateur:update" }
    requirements: { _method: post|put }

admin_utilisateur_utilisateur_delete:
    path:     /{id}/delete
    defaults: { _controller: "UtilisateurBundle:Utilisateur:delete" }
    requirements: { _method: post|delete }
