admin_sise_dano_index:
    path:     /
    defaults: { _controller: "SiseBundle:Dano:index" }
    methods:  GET

admin_sise_dano_show:
    path:     /{id}/show
    defaults: { _controller: "SiseBundle:Dano:show" }
    methods:  GET

admin_sise_dano_new:
    path:     /new
    defaults: { _controller: "SiseBundle:Dano:new" }
    methods:  [GET, POST]

admin_sise_dano_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiseBundle:Dano:edit" }
    methods:  [GET, POST]

admin_sise_dano_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseBundle:Dano:delete" }
    methods:  DELETE
