admin_sise_mail_index:
    path:     /
    defaults: { _controller: "SiseBundle:Mail:index" }
    methods:  GET

admin_sise_mail_show:
    path:     /{id}/show
    defaults: { _controller: "SiseBundle:Mail:show" }
    methods:  GET

admin_sise_mail_new:
    path:     /new
    defaults: { _controller: "SiseBundle:Mail:new" }
    methods:  [GET, POST]

admin_sise_mail_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiseBundle:Mail:edit" }
    methods:  [GET, POST]

admin_sise_mail_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiseBundle:Mail:delete" }
    methods:  DELETE
