admin_parametre_activite_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Activite:index" }
    methods:  GET

admin_parametre_activite_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Activite:show" }
    methods:  GET

admin_parametre_activite_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Activite:new" }
    methods:  [GET, POST]

admin_parametre_activite_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Activite:edit" }
    methods:  [GET, POST]

admin_parametre_activite_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Activite:delete" }
    methods:  DELETE
