admin_parametre_bailleur_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Bailleur:index" }
    methods:  GET

admin_parametre_bailleur_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Bailleur:show" }
    methods:  GET

admin_parametre_bailleur_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Bailleur:new" }
    methods:  [GET, POST]

admin_parametre_bailleur_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Bailleur:edit" }
    methods:  [GET, POST]

admin_parametre_bailleur_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Bailleur:delete" }
    methods:  DELETE
