admin_parametre_souscomposante_index:
    path:     /
    defaults: { _controller: "ParametreBundle:SousComposante:index" }
    methods:  [GET, POST]

admin_parametre_souscomposante_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:SousComposante:show" }
    methods:  GET

admin_parametre_souscomposante_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:SousComposante:new" }
    methods:  [GET, POST]

admin_parametre_souscomposante_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:SousComposante:edit" }
    methods:  [GET, POST]

admin_parametre_souscomposante_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:SousComposante:delete" }
    methods:  DELETE
