<?php

namespace PPCA\ParametreBundle\Repository;

/**
 * SousActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
