<?php

namespace PPCA\ParametreBundle\Repository;

/**
 * SousComposanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousComposanteRepository extends \Doctrine\ORM\EntityRepository
{
}
