<?php

namespace PPCA\SiseBundle\Repository;

/**
 * BlaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlaRepository extends \Doctrine\ORM\EntityRepository
{
}
