<?php

namespace PPCA\SiseBundle\Repository;

/**
 * DanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanoRepository extends \Doctrine\ORM\EntityRepository
{
}
