<?php

namespace PPCA\SiseBundle\Repository;

/**
 * HistoriqueDanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueDanoRepository extends \Doctrine\ORM\EntityRepository
{
}
