<?php

namespace PPCA\SiseBundle\Repository;

/**
 * PieceJointeDanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceJointeDanoRepository extends \Doctrine\ORM\EntityRepository
{
}
