<?php

namespace PPCA\SiseBundle\Repository;

/**
 * PieceJointeMailDanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceJointeMailDanoRepository extends \Doctrine\ORM\EntityRepository
{
}
