<?php

namespace PPCA\SiseBundle\Repository;

/**
 * PieceJointeMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceJointeMailRepository extends \Doctrine\ORM\EntityRepository
{
}
