<?php

namespace PPCA\SiseBundle\Repository;

/**
 * RequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteRepository extends \Doctrine\ORM\EntityRepository
{
}
